# Generated by Django 6.0 on 2025-12-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sync_id', models.TextField(unique=True)),
                ('codigo', models.TextField(unique=True)),
                ('nombre', models.TextField()),
                ('edificio', models.TextField(blank=True, null=True)),
                ('nivel', models.TextField(blank=True, null=True)),
                ('categoria', models.TextField(blank=True, null=True)),
                ('espacio', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.IntegerField(blank=True, null=True)),
                ('serie', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Activos',
                'db_table': 'activos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Auditorias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sync_id', models.TextField(unique=True)),
                ('espacio', models.TextField(blank=True, null=True)),
                ('fecha', models.TextField(blank=True, null=True)),
                ('total_esperados', models.IntegerField(blank=True, null=True)),
                ('total_escaneados', models.IntegerField(blank=True, null=True)),
                ('total_faltantes', models.IntegerField(blank=True, null=True)),
                ('total_sobrantes', models.IntegerField(blank=True, null=True)),
                ('codigos_escaneados', models.TextField(blank=True, null=True)),
                ('codigos_faltantes', models.TextField(blank=True, null=True)),
                ('codigos_sobrantes', models.TextField(blank=True, null=True)),
                ('estado', models.TextField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('plano_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Auditorías',
                'db_table': 'auditorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sync_id', models.TextField(unique=True)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('icono', models.TextField(blank=True, null=True)),
                ('color', models.TextField(blank=True, null=True)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
                'db_table': 'categorias',
                'managed': False,
            },
        ),
    ]
